export const projects = [
  {
    id: "ciana2601",
    name: "Ciana 2601",
    img: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    location: "Mulund, Mumbai"
  },
  {
    id: "ekta",
    name: "Ekta Residence",
    img: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    location: "Mumbai",
  },
  {
    id: "khot-house",
    name: "Khot House",
    img: "https://images.unsplash.com/photo-1505691723518-36a5ac3be353",
    location: "Maharashtra",
  },
  {
    id: "apex",
    name: "Apex Rubber Products",
    img: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    location: "Sanjan, Gujarat",
  },
  {
    id: "serenity-retreat",
    name: "Serenity Retreat House",
    img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    location: "Umbergaon",
  },
  {
    id: "zen-garden",
    name: "Serenity Landscape",
    img: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6",
    location: "Umbergaon",
  },
  {
    id: "parikh-house",
    name: "Parikh House",
    img: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6",
    location: "Daman",
  },
  {
    id: "white-villa",
    name: "White Classical Villa",
    img: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    location: "Umbergaon",
  },
];

// projectsData.js
// Central data source — import this in both Project.jsx and ProjectDetail.jsx

export const project_JSON = [
  {
    id: 1,
    name: "Ciana 2601",
    category: "Architectural Design",
    bwImage: "/project1_bwi.jpeg",
    colorImage: "/project1_colour.jpeg",
    bannerImage: "/project1_colour.jpeg", // full-width hero on detail page
    type: "Interior Design | Apartment Interior",
    area: "780 Sq. Ft. (Carpet Area)",
    year: "2024",
    location: "Ciana 2601, Tower D, Atmosphere, Mulund – Mumbai",
    description: [
      "This apartment showcases a chic design that transforms a space into a warm and inviting sanctuary.",
      "By creating a seamless open-concept environment, the original layout was reimagined by connecting the kitchen to the living area.",
      "The kitchen is a standout feature, with deep teal cabinets adorned with wicker-paneled shutters, adding an intriguing textural element.",
      "The living space is elevated by an eclectic mix of traditional and modern furniture, abstract art, and lush greenery, creating a cozy yet sophisticated ambiance.",
      "Natural materials, vibrant accents, strategic lighting, curved lines, and neutral walls blend together to create a unique visual narrative that enhances the space's functionality and aesthetic appeal.",
    ],
    galleryImages: [
      "/project1_g1.jpeg",
      "/project1_g2.jpeg",
      "/project1_g3.jpeg",
      "/project1_g4.jpeg",
      "/project1_g1.jpeg",
      "/project1_g2.jpeg",
    ],
  },
  {
    id: 2,
    name: "Ekta Residence",
    category: "Architectural Design",
    bwImage: "/project1_bwi.jpeg",
    colorImage: "/project1_colour.jpeg",
    bannerImage: "/project1_colour.jpeg",
    type: "Residential | Villa",
    area: "3200 Sq. Ft.",
    year: "2023",
    location: "Ekta Residences, Andheri West, Mumbai",
    description: [
      "Ekta Residence is a contemporary villa that merges indoor and outdoor living through expansive glazed facades.",
      "The design philosophy centers on biophilic principles — bringing nature into every corner through vertical gardens, natural stone, and timber accents.",
      "Each room flows naturally into the next, creating a sense of continuity and spatial generosity.",
    ],
    galleryImages: [
      "/project1_g1.jpeg",
      "/project1_g2.jpeg",
      "/project1_g3.jpeg",
      "/project1_g4.jpeg",
      "/project1_g1.jpeg",
      "/project1_g2.jpeg",
    ],
  },
  {
    id: 3,
    name: "Aarvi",
    category: "Architectural Design",
    bwImage: "/project1_bwi.jpeg",
    colorImage: "/project1_colour.jpeg",
    bannerImage: "/project1_colour.jpeg",
    type: "Residential | Bungalow",
    area: "4500 Sq. Ft.",
    year: "2023",
    location: "Aarvi Estate, Borivali, Mumbai",
    description: [
      "Aarvi is a modern bungalow that draws on clean geometric forms while remaining deeply rooted in contextual warmth.",
      "The facade composition plays with shadow and light through strategic horizontal cantilevering.",
      "Interiors are designed with curated material palettes — travertine, warm oak, and matte plaster — creating a timeless elegance.",
    ],
    galleryImages: [
     "/project1_g1.jpeg",
      "/project1_g2.jpeg",
      "/project1_g3.jpeg",
      "/project1_g4.jpeg",
      "/project1_g1.jpeg",
      "/project1_g2.jpeg",
    ],
  },
  {
    id: 4,
    name: "Classic Villa",
    category: "Architectural Design",
    bwImage: "/project1_bwi.jpeg",
    colorImage: "/project1_colour.jpeg",
    bannerImage: "/project1_colour.jpeg",
    type: "Residential | Classical Villa",
    area: "6800 Sq. Ft.",
    year: "2022",
    location: "Classic Villa, Juhu, Mumbai",
    description: [
      "Classic Villa is a grand residence that reimagines neoclassical architecture for the modern age.",
      "Symmetrical facades, grand columns, and ornate detailing are balanced with contemporary spatial planning and open interiors.",
      "The landscape design features a central fountain court that creates a powerful axial entry experience.",
    ],
    galleryImages: [
    "/project1_g1.jpeg",
      "/project1_g2.jpeg",
      "/project1_g3.jpeg",
      "/project1_g4.jpeg",
      "/project1_g1.jpeg",
      "/project1_g2.jpeg",
    ],
  },
  {
    id: 5,
    name: "Meridian",
    category: "Architectural Design",
    bwImage: "/project1_bwi.jpeg",
    colorImage: "/project1_colour.jpeg",
    bannerImage: "/project1_colour.jpeg",
    type: "Commercial | Mixed-Use",
    area: "22,000 Sq. Ft.",
    year: "2024",
    location: "Meridian Complex, BKC, Mumbai",
    description: [
      "Meridian is a premium mixed-use development designed to redefine the commercial skyline of Bandra Kurla Complex.",
      "The tower's curtain wall system creates an ever-changing facade that reflects the city's dynamic energy.",
      "Ground-level retail, co-working spaces, and sky lobbies are seamlessly integrated into a vertical urban ecosystem.",
    ],
    galleryImages: [
     "/project1_g1.jpeg",
      "/project1_g2.jpeg",
      "/project1_g3.jpeg",
      "/project1_g4.jpeg",
      "/project1_g1.jpeg",
      "/project1_g2.jpeg",
    ],
  },
  {
    id: 6,
    name: "Elysian Beauty",
    category: "Architectural Design",
    bwImage: "/project1_bwi.jpeg",
    colorImage: "/project1_colour.jpeg",
    bannerImage: "/project1_colour.jpeg",
    type: "Commercial | Retail Interior",
    area: "1200 Sq. Ft.",
    year: "2024",
    location: "Elysian Beauty Studio, Powai, Mumbai",
    description: [
      "Elysian Beauty is a luxury retail interior that transforms the shopping experience into a sensorial journey.",
      "Arched niches, curated product displays, and warm ambient lighting create an atmosphere of refined indulgence.",
      "Every material — from fluted glass shelving to polished terrazzo floors — was selected to reinforce the brand's identity of elegance and precision.",
    ],
    galleryImages: [
     "/project1_g1.jpeg",
      "/project1_g2.jpeg",
      "/project1_g3.jpeg",
      "/project1_g4.jpeg",
      "/project1_g1.jpeg",
      "/project1_g2.jpeg",
    ],
  },
];